### ISSUE TITLE
Can't use more than one slab when striping

### ISSUE THREAD

**Issue by Joelgranados** [OpenMPDK/FlexAlloc#11]
This is the way I reproduced:
1. Just up the number of writes with bw_tester and see the performance drop
I also printed out the number of slabs present in the FS once we had finished the benchmark and it still said 1 even though we wrote much more than what the slab could take.
`sudo mkfs.flexalloc /dev/ng3n1 -s 3145728 -p 1 --md_dev=/dev/ng3n2 ; sudo ./bw_tester /dev/ng3n1 /dev/ng3n2 ---
[sudo] password for joel: 
Opts:
  dev_uri: /dev/ng3n1
  slab_nlb: 3145728
  verbose: 0
  md_dev_uri: /dev/ng3n2
throughput : 1
===============
Pool Entry 0x565101624000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x565101625000
===============

===============
Pool Entry 0x565101624000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x565101625000
===============
joel@joelS2 ~/src/benchmarking/flexalloc_object_striping (master●●)$ sudo mkfs.flexalloc /dev/ng3n1 -s 3145728 -p 1 --md_dev=/dev/ng3n2 ; sudo ./bw_tester /dev/ng3n1 /dev/ng3n2 ---
Opts:
  dev_uri: /dev/ng3n1
  slab_nlb: 3145728
  verbose: 0
  md_dev_uri: /dev/ng3n2
throughput 1/2.5
===============
Pool Entry 0x56083bdec000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x56083bded000
===============
...
===============
Pool Entry 0x56083bdec000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x56083bded000
===============
joel@joelS2 ~/src/benchmarking/flexalloc_object_striping (master●●)$ sudo mkfs.flexalloc /dev/ng3n1 -s 3145728 -p 1 --md_dev=/dev/ng3n2 ; sudo ./bw_tester /dev/ng3n1 /dev/ng3n2 ---
Opts:
  dev_uri: /dev/ng3n1
  slab_nlb: 3145728
  verbose: 0
  md_dev_uri: /dev/ng3n2
throughput 1/2.7
===============
Pool Entry 0x5639d5fe8000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x5639d5fe9000
===============
...
===============
Pool Entry 0x5639d5fe8000
* Head : 2147483647, offset 0
* Head : 2147483647, offset 1
* Head : 0, offset 2
`-->next : 2147483647, prev : 2147483647, maxcount : 128, refcount : 1, ptr 0x5639d5fe9000
===============`

**Comment by Joelgranados** [comment]
The function "fla_object_create" assumes that it can "create" an object if there is at least one left in the slab. With the addition of striping, we need to create strp_num consecutive objects. If there are not enough objects in the slab, we need to get a new slab which can house all the consecutive objects. This is missing because if fla_slab_next_available_obj fails due to not enough space for strp_num objects, we return failure instead of searching for another slab to house the consecutive objects.

This actually has a deeper implication in the way we categorize the slabs. We have free slabs (no objects in them), partial slabs (at least one object free) and full slabs (no free objects). With striping this changes because the slab could be unusable (cannot house more striped objects) and at the same time have a free object.

**Comment by nmtadam** [comment]
Quick background info, I tested using one large slab and did not attempt to leverage multiple slabs. This is a good catch.

Let me paraphrase you so I can help review the code. BTW I am seeing two issues.

1. Once we fill up one slab no attempt will be made to get another slab, forcing a pool using striped objects to only use one pool. 
2. A slab using striped objects leaves some objects unusable if the slab capacity does not evenly divide the number of objects used for a striped object.

1 seems like an issue we need to fix and 2 seems like a consequence of using striped objects with the wrong parameters. Let me know what you think.

**Comment by Joelgranados** [comment]
> 1. Once we fill up one slab no attempt will be made to get another slab, forcing a pool using striped objects to only use one pool.
In my tests I saw it fail. forcing the pool using striped objects to fail if more objects are created

> 2. A slab using striped objects leaves some objects unusable if the slab capacity does not evenly divide the number of objects used for a striped object.
This is true, but this is not what is handled in this task. We can start another task for that.

> 1 seems like an issue we need to fix and 2 seems like a consequence of using striped objects with the wrong parameters. Let me know what you think.
Correct. Issue 2 can be handled in mkfs time. We can hint that we will be using striping and help the user to prevent to loose to many objects.

**Comment by Joelgranados** [comment]
This is already solved in master
