### ISSUE TITLE
We need an easy way to change the backend.

### ISSUE THREAD

**Issue by Joelgranados** [OpenMPDK/FlexAlloc#12]
ATM there is no way to define the backend used by xnvme.
I'm imaginning something like fla_storage_backend_set(const * char name)

**Comment by nmtadam** [comment]
I had a pull request related to this, it got closed when I deleted a branch. I'll revive. I want to pass options on the open call.

**Comment by nmtadam** [comment]
PR #13 was merged and fixes this issue
