### ISSUE TITLE
FlexAlloc Daemon Verbose Option

### ISSUE THREAD

**Issue by nmtadam** [OpenMPDK/FlexAlloc#19]
@jwdevantier I see this getting set but not used, my compiler also warns me about it.

../src/flexalloc_daemon.c:125:7: warning: variable ‘verbose’ set but not used [-Wunused-but-set-variable]
  125 |   int verbose = 0;

Was wondering if there are plans to use this, otherwise I think we should rip it out.

**Comment by Joelgranados** [comment]
I have fixed this
