### ISSUE TITLE
Flexalloc fails when striping in conventional name space ssd and using the io_uring_cmd interface.

### ISSUE THREAD

**Issue by Joelgranados** [OpenMPDK/FlexAlloc#23]
Way to reproduce.
1. setup a md device on a conventional NS.
2. create a stripped pool
3. set the backend to "io_uring_cmd"
4. watch it fail when you do a write that goes over the (non-stripped) object size.

**Comment by nmtadam** [comment]
Did you try to use the block interface? io_uring_cmd is only compatible with the char interface, things look normal to me if I point to the char interface.

**Comment by Joelgranados** [comment]
This should work with the current char device implementation. make sure you use the ng* devices instead of the nvme ones.
