### ISSUE TITLE
Flan Crashes when the first root object if full

### ISSUE THREAD

**Issue by Joelgranados** [OpenMPDK/FlexAlloc#61]
This was first reported by Adrian Borup here https://discord.com/channels/778163622324338688/912979850040590346/1103331497810853908
Here is what he wrote on Discord:
"""
Hey. Here is a C file that illustrates the crash, and a script that creates a loopback device and runs the code (The libflan.a path needs to be changed as its hardcoded). This is all running on the jag/flanv2 branch, with xNVMe on it's next branch.

The bash file allows you to mess with the block size and count, my current results are:
- 4096 bytes, 64 blocks, 32 pr slab = Crashes when opening the 30th block (29th index)
- 4096 bytes, 32 blocks, 16 pr slab = Crashes when opening the 15th block (14th index)
- 2048 bytes, 64 blocks, 32 pr slab = Crashes when opening the 15th block (14th index)
- 2048 bytes, 32 blocks, 16 pr slab = Crashes when opening the 15th block (14th index)
"""

**Comment by Joelgranados** [comment]
Here is the bash script:
`#! /usr/bin/bash
backing_file="$(mktemp)_flexnvme"

# Block size cannot go above 4096
block_size=4096
#block_size=2048

block_count=64
slab_block_count=32

echo "Creating backing file: $backing_file"

sudo dd if=/dev/zero of=$backing_file bs=$block_size count=$block_count
sudo losetup -fP -b $block_size $backing_file
loopback_device=$(losetup --output=NAME -j "$backing_file" | tail -1)

if [ -z "$loopback_device" ]; then
  echo "Failed to find loopback device"
  sudo rm $backing_file
  exit 1
fi

sudo mkfs.flexalloc -s $slab_block_count $loopback_device

LIBFLAN=~/Code/the-whole-project/build/flexalloc-build/flan/libflan.a # should be able to replace with -lflan
FILES=block_count.c
TARGET=block_count

gcc $FILES $LIBFLAN $(pkg-config --libs xnvme) -o $TARGET -Wall -g
sudo ./$TARGET $loopback_device $block_size

sudo losetup -d $loopback_device
sudo rm $backing_file`

**Comment by Joelgranados** [comment]
Here is the C file
`#include "flan.h"
#include <stdio.h>

#define POOL_NAME "DEMO_POOL"
// Fails when opening object 29
#define OBJ_COUNT_TO_WRITE 30

int main(int argc, char *argv[]) {
  uint64_t obj_size = 4096;
  char *device_uri = NULL;
  char *obj_name = NULL;

  if (argc == 3) {
    device_uri = argv[1];
    obj_size = atoi(argv[2]);
  } else {
    printf("Usage: %s [device_uri] [obj_size]\n", argv[0]);
    return 1;
  }


  struct fla_pool_create_arg pool_arg =
  {
    .flags = 0,
    .name = POOL_NAME,
    .name_len = strlen(POOL_NAME),
    .obj_nlb = 0, // will get set by flan_init
    .strp_nobjs = 0,
    .strp_nbytes = 0
  };

  printf("Opening flan\n");
  struct flan_handle *flanh = NULL;
  if (flan_init(device_uri, NULL, &pool_arg, obj_size, &flanh)) {
    perror("Failed to initialise flan\n");
    goto end;
  }
  printf("Initialised flan\n");

  for (int i = 0; i < OBJ_COUNT_TO_WRITE; i++) {
    char *obj_name = flan_buf_alloc(FLAN_OBJ_NAME_LEN_MAX, flanh);
    if (!obj_name) {
      perror("Failed to allocate name buffer\n");
      goto end;
    }

    // we just arbitrarily choose an object name format: "DEMO_OBJ_.<some id>"
    snprintf(obj_name, FLAN_OBJ_NAME_LEN_MAX, "DEMO_OBJ_%d", i);

    char *buf = flan_buf_alloc(obj_size, flanh);
    if (!buf) {
      perror("Failed to allocate buffer\n");
      goto end;
    }

    printf("Opening object %s\n", obj_name);
    uint64_t obj_handle;
    if (flan_object_open(obj_name, flanh, &obj_handle, FLAN_OPEN_FLAG_CREATE | FLAN_OPEN_FLAG_WRITE)) {
      perror("Failed to open object");
      goto end;
    }

    printf("Writing data\n");
    for (int j = 0; j < obj_size; j++) {
      buf[j] = '0' + (j % 10);
    }
    // Print the buffer
    for (int j = 0; j < obj_size; j++) {
      printf("%c", buf[j]);
    }
    printf("\n");

    if (flan_object_write(obj_handle, buf, 0, obj_size, flanh)) {
      perror("Failed to write object");
      goto end;
    }

    printf("Closing object %s\n", obj_name);
    if (flan_object_close(obj_handle, flanh)) {
      perror("Failed to close object");
      goto end;
    }
  }

end:
  if (flanh) {
    printf("Closing flan\n");
    flan_close(flanh);
  }

  if (obj_name) {
    free(obj_name);
  }

  return 0;
}`

**Comment by avborup** [comment]
I can confirm that with #62, we are able to store double the amount of objects, which makes sense since the number of root objects has gone from 1 to 2.

I've tested with some of the same configurations listed above, and they seem to work. For example, block size 4096, 64 blocks, object size 4096, and slab size 32 now allows us to write 59 objects rather than 29.

Regarding the potential issues with syncing to disk, we will get back to you on that. Edit: [was confirmed to work on Discord](https://discord.com/channels/778163622324338688/912979850040590346/1105217632375947404).

**Comment by Joelgranados** [comment]
I have pushed the fix. closing for now
