### ISSUE TITLE
Can FlexAlloc support non-ZNS type SSDs

### ISSUE THREAD

**Issue by benqwu** [OpenMPDK/FlexAlloc#66]
Can FlexAlloc support non-ZNS type SSDs, and what is the performance impact?

**Comment by Joelgranados** [comment]
FlexAlloc supports ZNS and FDP and CNS and can probably support things like streams with minimal changes.

What you pay for performance depends on how you use it. We have mostly used it to test HW and it has been very useful measuring WAF.

Please go to our public Discord if you have more questions: https://discord.com/channels/778163622324338688/912979850040590346
